### ISSUE TITLE
devcontainerの環境を用意する

### ISSUE THREAD

**Issue by Cer0un0** [ShphieEnterprise/Sophie#4]
下記のLinter, Formatterを具備したdevcontainerの環境を作る
* flake8
* black
* isort
* editorconfig

**Comment by satory074** [comment]
これpipでinstallするライブラリはdevcontainerで指定しているわけではないんでしょうか？

**Comment by Cer0un0** [comment]
> これpipでinstallするライブラリはdevcontainerで指定しているわけではないんでしょうか？

質問の意図を教えてください。

**Comment by satory074** [comment]
こわ

**Comment by satory074** [comment]
面接で言われたくない聞き返し第1位

**Comment by satory074** [comment]
devcontainerの環境構築・実行はできたのですが、pipのライブラリは、設定ファイルに依存しているのか、ユーザのローカルの環境に依存しているのか気になりました

**Comment by satory074** [comment]
```json
"postCreateCommand": "pip install -r requirements.txt",
```

`devcontainer.json`に見つけました

**Comment by Cer0un0** [comment]
> devcontainerの環境構築・実行はできたのですが、pipのライブラリは、設定ファイルに依存しているのか、ユーザのローカルの環境に依存しているのか気になりました

Dockerfileに記載されているイメージに内包されているモジュールと、requirements.txtのモジュールが入っているはず？

pip freezeなどして合ってるかみてみてください。

**Comment by satory074** [comment]
たぶんそうと思います

```bash
devuser@689f29b047fe:/workspaces/Sophie$ pip freeze
aiohttp==3.8.5
aiosignal==1.3.1
async-timeout==4.0.3
attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
discord.py==2.1.0
flake8==6.1.0
frozenlist==1.4.0
idna==3.4
mccabe==0.7.0
multidict==6.0.4
openai==0.27.0
pycodestyle==2.11.0
pyflakes==3.1.0
requests==2.31.0
tqdm==4.66.1
urllib3==2.0.4
yarl==1.9.2
```

**Comment by satory074** [comment]
細かい点等気づいたら適宜issueを立てますが、特に動作問題ないかと思いますので、#10mergeしておきます。
